version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: your-project-name
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - database

    database:
        image: postgres:latest
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        volumes:
            - pg_data:/var/lib/postgresql/data

    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

volumes:
    pg_data:
